import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { UserContextProvider } from "@/hooks/useUserContext";
import QueryClientProvider from "@/components/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todos App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <UserContextProvider>
            <div className="flex flex-col h-screen bg-slate-100">
              <Navbar />
              {children}
              <Toaster position="top-right" />
            </div>
          </UserContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
